import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { appendFileSync, copyFileSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const cliSource = '086dc1f16ffe57694ff806df8ff51cf1d0cf072e';
const actionSource = '8b026e9c7268a960ed6f9b48ecea404180ddb151';
const source = resolve(process.env.ROOTFORM_ACTION_SOURCE || 'fixtures/action');
const { combineReports, renderReport, REPORT_MARKER } = await import(pathToFileURL(resolve(source, 'src/report.ts')).href);
const { readGitHubContext, upsertPullRequestComment } = await import(pathToFileURL(resolve(source, 'src/pull-request.ts')).href);
const required = (name: string) => {
  const value = process.env[name];
  assert.ok(value, `${name} is required`);
  return value;
};
const digest = (path: string) => createHash('sha256').update(readFileSync(path)).digest('hex');

if (process.argv[2] === 'assemble') {
  assert.equal(process.env.STEP_OUTCOME, 'failure', 'the negative Policy gate must fail');
  const original = required('ROOTFORM_INPUT_FORM');
  assert.deepEqual(readFileSync('rendered/form.json'), readFileSync(original), 'reopening must preserve exact Form bytes');
  assert.ok(readFileSync('scripts/markdown-review/go.mod', 'utf8').includes(`-${cliSource.slice(0, 12)}`));
  assert.deepEqual(readFileSync('rendered/result.json'), readFileSync(required('ROOTFORM_POLICY_RESULT')), 'Policy rendering must preserve the actual recorded result bytes');
  const report = combineReports([required('ROOTFORM_ARCHITECTURE'), required('ROOTFORM_POLICY_REPORT')], 'rendered');
  assert.equal(report, 'rendered/report.md');
  const markdown = readFileSync(report, 'utf8');
  assert.equal((markdown.match(/^## Rootform$/gm) || []).length, 1);
  assert.deepEqual([...markdown.matchAll(/^### (.+)$/gm)].map(match => match[1]), ['Architecture', 'Policies', 'Details']);
  assert.equal((markdown.match(/^---$/gm) || []).length, 2);
  assert.ok(!/^# |^#####|^#### (?:Uncertainty|Incomplete coverage|Without target|`)/m.test(markdown));
  assert.ok(!markdown.includes('Each list above shows at most'));
  assert.ok(!/\d+ of \d+ (?:entries|evaluations|evidence lines) shown|\(\d+ of \d+ shown\)/.test(markdown));
  assert.ok(markdown.includes('> [!CAUTION]\n> **Verdict: VIOLATED**'));
  assert.ok(markdown.includes('<summary>Instances: 76 added</summary>'));
  for (const heading of ['#### ± Planned changes', '#### ↺ Reported drift', '#### Δ Net change', '#### ▦ Planned architecture', '**? Uncertainty']) {
    assert.ok(markdown.includes(heading), `missing review typography: ${heading}`);
  }
  for (const [variable, filename] of [['ROOTFORM_SARIF', 'results.sarif'], ['ROOTFORM_HTML', 'explorer.html']]) {
    copyFileSync(required(variable), `rendered/${filename}`);
  }
  writeFileSync('rendered/provenance.json', JSON.stringify({
    format_version: '1',
    review_cli_source: cliSource,
    action_source: actionSource,
    semantic_cli_release: '0.1.0-pr.117.1',
    architecture_report_sha256: digest(required('ROOTFORM_ARCHITECTURE')),
    form_sha256: digest('rendered/form.json'),
    report_sha256: digest('rendered/report.md'),
    policy_report_sha256: digest(required('ROOTFORM_POLICY_REPORT')),
    policy_result_sha256: digest('rendered/result.json'),
    note: 'Review Markdown is generated by the exact public CLI source from the actual released-binary Form and recorded Policy answer. Form and Policy result bytes remain identical; no compilation or new Policy evaluation occurs in the presentation embedding. This is source report qualification, not a new distributed candidate.'
  }, null, 2) + '\n');
} else if (process.argv[2] === 'publish') {
  const context = readGitHubContext();
  const body = renderReport({
    version: `source-${cliSource.slice(0, 7)}`,
    markdown: readFileSync('rendered/report.md', 'utf8'),
    workflowUrl: context.workflowUrl,
    artifactUrl: required('ROOTFORM_ARTIFACT_URL')
  });
  appendFileSync(required('GITHUB_STEP_SUMMARY'), `${body}\n`);
  if (context.eventName === 'pull_request' && context.pullRequest?.sameRepository) {
    const result = await upsertPullRequestComment({
      token: required('GITHUB_TOKEN'), identity: context.pullRequest,
      body: `${REPORT_MARKER}\n${body}`,
      runId: context.runId, runAttempt: context.runAttempt
    });
    console.log(JSON.stringify(result));
  }
} else {
  throw new Error('usage: publish-review.ts assemble|publish');
}
