import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { appendFileSync, copyFileSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const cliSource = '7f0ef17c418f76754ddd20d6a48310a0b257d17b';
const actionSource = '17cf0cbefae80ac388b54e0329dd40f3cd0f659e';
const source = resolve(process.env.ROOTFORM_ACTION_SOURCE || 'fixtures/action');
const { combineReports, renderReport, REPORT_MARKER } = await import(pathToFileURL(resolve(source, 'src/report.ts')).href);
const { readGitHubContext, upsertPullRequestComment } = await import(pathToFileURL(resolve(source, 'src/pull-request.ts')).href);
const required = (name: string) => {
  const value = process.env[name];
  assert.ok(value, `${name} is required`);
  return value;
};
const digest = (path: string) => createHash('sha256').update(readFileSync(path)).digest('hex');

if (process.argv[2] === 'assemble') {
  assert.equal(process.env.STEP_OUTCOME, 'failure', 'the negative Policy gate must fail');
  const original = required('ROOTFORM_INPUT_FORM');
  assert.deepEqual(readFileSync('rendered/form.json'), readFileSync(original), 'reopening must preserve exact Form bytes');
  assert.ok(readFileSync('scripts/markdown-review/go.mod', 'utf8').includes('v0.0.0-20261002141911-7f0ef17c418f'));
  const report = combineReports([required('ROOTFORM_ARCHITECTURE'), required('ROOTFORM_POLICY_REPORT')], 'rendered');
  assert.equal(report, 'rendered/report.md');
  for (const [variable, filename] of [['ROOTFORM_POLICY_RESULT', 'result.json'], ['ROOTFORM_SARIF', 'results.sarif'], ['ROOTFORM_HTML', 'explorer.html']]) {
    copyFileSync(required(variable), `rendered/${filename}`);
  }
  writeFileSync('rendered/provenance.json', JSON.stringify({
    format_version: '1',
    architecture_cli_source: cliSource,
    action_source: actionSource,
    semantic_cli_release: '0.1.0-pr.117.1',
    architecture_report_sha256: digest(required('ROOTFORM_ARCHITECTURE')),
    form_sha256: digest('rendered/form.json'),
    report_sha256: digest('rendered/report.md'),
    policy_report_sha256: digest(required('ROOTFORM_POLICY_REPORT')),
    note: 'Architecture Markdown is generated by the public CLI source from the actual released-binary Form. The unchanged single-side Policy report comes from the published CLI. This is source report qualification, not a new distributed candidate.'
  }, null, 2) + '\n');
} else if (process.argv[2] === 'publish') {
  const context = readGitHubContext();
  const body = renderReport({
    version: `source-${cliSource.slice(0, 7)}`,
    markdown: readFileSync('rendered/report.md', 'utf8'),
    workflowUrl: context.workflowUrl,
    artifactUrl: required('ROOTFORM_ARTIFACT_URL')
  });
  appendFileSync(required('GITHUB_STEP_SUMMARY'), `${body}\n`);
  if (context.eventName === 'pull_request' && context.pullRequest?.sameRepository) {
    const result = await upsertPullRequestComment({
      token: required('GITHUB_TOKEN'), identity: context.pullRequest,
      body: `${REPORT_MARKER}\n${body}`,
      runId: context.runId, runAttempt: context.runAttempt
    });
    console.log(JSON.stringify(result));
  }
} else {
  throw new Error('usage: publish-review.ts assemble|publish');
}
